/*
 * Product Image Classification API
 * The model for this service was obtained by retraining the Image Classifier on approx. 50k Icecat images. There are 29 categories available: antivirus_security_software, computer_monitors_slash_workstations, digital_cameras, external_hard_drives, graphics_cards, internal_hard_drives, keyboards, LED_TVs, memory_modules, mice, mobile_device_chargers, motherboards, mounting_kits, network_switches, networking_cables, networking_cards, notebooks_and_accessories, other, power_adapters, power_cables, printers_and_accessories, processors, projection_screens, rechargeable_batteries, servers, smartphones, tablets, uninterruptible_power_supplies, USB_flash_drives_and_accessories.
 *
 * OpenAPI spec version: Alpha
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.client.auth;

import com.sap.apibhub.sdk.client.Pair;

import com.squareup.okhttp.Credentials;

import java.util.Map;
import java.util.List;

import java.io.UnsupportedEncodingException;

public class HttpBasicAuth implements Authentication {
    private String username;
    private String password;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public void applyToParams(List<Pair> queryParams, Map<String, String> headerParams) {
        if (username == null && password == null) {
            return;
        }
        headerParams.put("Authorization", Credentials.basic(
            username == null ? "" : username,
            password == null ? "" : password));
    }
}
